version: '3.8'

services:
  trino:
    image: trinodb/trino:435
    container_name: data-hub-trino
    restart: unless-stopped
    ports:
      - "8089:8080"
    volumes:
      - ./config/trino/catalog:/etc/trino/catalog
      - ./config/trino/config.properties:/etc/trino/config.properties
      - ./config/trino/jvm.config:/etc/trino/jvm.config
    environment:
      TRINO_MEMORY: 2GB
    depends_on:
      - hive-metastore
      - minio
    networks:
      data-hub:
        ipv4_address: 172.28.1.30
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "trino", "--execute", "SELECT 1"]