#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE airflow;
    CREATE DATABASE hive_metastore;
    CREATE DATABASE trino;
    GRANT ALL PRIVILEGES ON DATABASE airflow TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE hive_metastore TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE trino TO $POSTGRES_USER;
EOSQL